[workspace]

[package]
name = "password-validity-checker-methods-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm-guest = "0.9"

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-build = "0.9"
