[package]
name = "digital-signature-core"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkp = { version = "0.12", default-features = false }
serde = { version = "1.0", default-features = false }
