[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.11"

[dependencies]
# chess = "3.2"
shakmaty = "0.22"
risc0-zkvm-guest = "0.11"
chess-core = { path = "../../core" }
