[package]
name = "password-validity-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
password-validity-checker-core = { path = "../core" }
password-validity-checker-methods = { path = "../methods" }
rand = "0.8"
risc0-zkvm-host = "0.10"
risc0-zkvm-core = "0.10"
risc0-zkvm-serde = "0.10"
