[package]
name = "guest"
version = "0.12.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.12"

[dependencies]
json-core = { path = "../../core" }
risc0-zkvm = { version = "0.12", default-features = false, features = [ "std" ] }
json = "0.12"
