[workspace]
members = [
    "core",
    "host",
    "methods",
]

[profile.release]
opt-level = 3

[patch.crates-io]
# TODO(victor): Remove these patch definitions when 8bd948b is included in a release.
risc0-zkp = { git = "https://github.com/risc0/risc0", rev = "8bd948be64d6084d1f01b37d60073f920c9beaed" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "8bd948be64d6084d1f01b37d60073f920c9beaed" }
risc0-build = { git = "https://github.com/risc0/risc0", rev = "8bd948be64d6084d1f01b37d60073f920c9beaed" }
