[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { git = "ssh://git@github.com/risc0/risc0.git", rev = "9a3865a5a54ec1e974250c785545a6bf727f6949" }

[package.metadata.risc0]
methods = ["guest"]
