[package]
name = "digital-signature-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.18"
env_logger = "0.9.0"
log = "0.4.17"
digital-signature-methods = { path = "../methods" }
digital-signature-core = { path = "../core" }
risc0-zkvm-core = "0.7.2"
risc0-zkvm-host = "0.7.2"
risc0-zkvm-serde = "0.7.2"
serde = "1.0"
sha2 = "0.10.2"
tempfile = "3.3"
