[workspace]

[package]
name = "voting-machine-methods-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
voting-machine-core = { path = "../../core" }
risc0-zkvm-guest = "0.7"

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-build = "0.7"
