name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, "Linux"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo run --manifest-path digital-signature -p risc0-build-methods
      - run: cargo test --manifest-path digital-signature
      - run: echo "All done"

