name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        project:
          - digital-signature
          - password-checker
          - voting-machine
        os: [Linux, macOS]
    runs-on: [self-hosted, "${{ matrix.os }}"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all -- --check
        working-directory: ${{ matrix.project }} 
      - run: cargo test --release
        working-directory: ${{ matrix.project }}
